---
metadata:
  schema_version: 0.2
  name: "model-settings"
  daily_load: 28
  generated:
    inputs: [103396835_All-Web-Site-Data]
    host: http://skipjaq.com/
    date: 2017-11-02T15:07:25.694Z
    generation_time: 2.274s

configuration:
  model_entry: "scn-103396835"
  cookie_policy: "forget"
  follow_redirects: true

requests:
  req-103396835-14:
    http:
      method: GET
      path: "/jobs/pl/staff_engineer"
  req-103396835-10:
    http:
      method: GET
      path: "/jobs"
  req-103396835-13:
    http:
      method: GET
      path: "/jobs/pl/"
  req-103396835-12:
    http:
      method: GET
      path: "/offices"
  req-103396835-17:
    http:
      method: GET
      path: "/jobs.html"
  req-103396835-20:
    http:
      method: GET
      path: "/hiring.html"
  req-103396835-8:
    http:
      method: GET
      path: "/work"
  req-103396835-6:
    http:
      method: GET
      path: "/"
  req-103396835-16:
    http:
      method: GET
      path: "/brand.html"
  req-103396835-15:
    http:
      method: GET
      path: "/case-studies"
  req-103396835-2:
    http:
      method: GET
      path: "/team"
  req-103396835-4:
    http:
      method: GET
      path: "/pricing"
  req-103396835-5:
    http:
      method: GET
      path: "/jobs/uk/senior_staff_engineer"
  req-103396835-3:
    http:
      method: GET
      path: "/board"
  req-103396835-7:
    http:
      method: GET
      path: "/works"
  req-103396835-18:
    http:
      method: GET
      path: "/funding"
  req-103396835-9:
    http:
      method: GET
      path: "/%20funding"
  req-103396835-11:
    http:
      method: GET
      path: "/management"
  req-103396835-1:
    http:
      method: GET
      path: "/take-the-tour"
  req-103396835-19:
    http:
      method: GET
      path: "/jobs/"

scenarios:
  scn-103396835:
    requestgraph:
      entries:
        req-103396835-1: 0.008321
        req-103396835-10: 0.102635
        req-103396835-11: 0.011095
        req-103396835-12: 0.017337
        req-103396835-14: 0.003467
        req-103396835-15: 0.014563
        req-103396835-16: 0.001386
        req-103396835-2: 0.017337
        req-103396835-3: 0.007628
        req-103396835-4: 0.009015
        req-103396835-5: 0.005547
        req-103396835-6: 0.80097
        req-103396835-9: 0.000693
      edges:
        req-103396835-1:
          req-103396835-2:
            probability: 0.076335
            holding:
              fixed:
                delay: 82.765625
          req-103396835-1:
            probability: 0.015267
            holding:
              fixed:
                delay: 82.765625
          req-103396835-15:
            probability: 0.122137
            holding:
              fixed:
                delay: 82.765625
          req-103396835-4:
            probability: 0.076335
            holding:
              fixed:
                delay: 82.765625
          req-103396835-6:
            probability: 0.12977
            holding:
              fixed:
                delay: 82.765625
          req-103396835-12:
            probability: 0.038167
            holding:
              fixed:
                delay: 82.765625
          req-103396835-10:
            probability: 0.030534
            holding:
              fixed:
                delay: 82.765625
        req-103396835-10:
          req-103396835-4:
            probability: 0.004255
            holding:
              fixed:
                delay: 57
          req-103396835-14:
            probability: 0.085106
            holding:
              fixed:
                delay: 57
          req-103396835-6:
            probability: 0.068085
            holding:
              fixed:
                delay: 57
          req-103396835-11:
            probability: 0.004255
            holding:
              fixed:
                delay: 57
          req-103396835-12:
            probability: 0.029787
            holding:
              fixed:
                delay: 57
          req-103396835-2:
            probability: 0.029787
            holding:
              fixed:
                delay: 57
          req-103396835-5:
            probability: 0.085106
            holding:
              fixed:
                delay: 57
          req-103396835-15:
            probability: 0.004255
            holding:
              fixed:
                delay: 57
        req-103396835-11:
          req-103396835-3:
            probability: 0.445544
            holding:
              fixed:
                delay: 93.037974
          req-103396835-10:
            probability: 0.019801
            holding:
              fixed:
                delay: 93.037974
          req-103396835-2:
            probability: 0.178217
            holding:
              fixed:
                delay: 93.037974
          req-103396835-6:
            probability: 0.089108
            holding:
              fixed:
                delay: 93.037974
          req-103396835-12:
            probability: 0.029702
            holding:
              fixed:
                delay: 93.037974
          req-103396835-17:
            probability: 0.019801
            holding:
              fixed:
                delay: 93.037974
        req-103396835-12:
          req-103396835-1:
            probability: 0.024193
            holding:
              fixed:
                delay: 73.014925
          req-103396835-10:
            probability: 0.07258
            holding:
              fixed:
                delay: 73.014925
          req-103396835-6:
            probability: 0.153225
            holding:
              fixed:
                delay: 73.014925
          req-103396835-4:
            probability: 0.008064
            holding:
              fixed:
                delay: 73.014925
          req-103396835-2:
            probability: 0.241935
            holding:
              fixed:
                delay: 73.014925
          req-103396835-15:
            probability: 0.008064
            holding:
              fixed:
                delay: 73.014925
          req-103396835-11:
            probability: 0.016129
            holding:
              fixed:
                delay: 73.014925
          req-103396835-3:
            probability: 0.016129
            holding:
              fixed:
                delay: 73.014925
        req-103396835-13:
          req-103396835-19:
            probability: 1
            holding:
              fixed:
                delay: 8
        req-103396835-14:
          req-103396835-10:
            probability: 0.038461
            holding:
              fixed:
                delay: 153
          req-103396835-2:
            probability: 0.076923
            holding:
              fixed:
                delay: 153
          req-103396835-6:
            probability: 0.038461
            holding:
              fixed:
                delay: 153
          req-103396835-13:
            probability: 0.038461
            holding:
              fixed:
                delay: 153
        req-103396835-15:
          req-103396835-12:
            probability: 0.042253
            holding:
              fixed:
                delay: 94.543209
          req-103396835-6:
            probability: 0.169014
            holding:
              fixed:
                delay: 94.543209
          req-103396835-2:
            probability: 0.06338
            holding:
              fixed:
                delay: 94.543209
          req-103396835-1:
            probability: 0.147887
            holding:
              fixed:
                delay: 94.543209
          req-103396835-10:
            probability: 0.042253
            holding:
              fixed:
                delay: 94.543209
          req-103396835-4:
            probability: 0.049295
            holding:
              fixed:
                delay: 94.543209
          req-103396835-15:
            probability: 0.056338
            holding:
              fixed:
                delay: 94.543209
        req-103396835-16:
          req-103396835-16:
            probability: 0.333333
            holding:
              fixed:
                delay: 1716
        req-103396835-17:
          req-103396835-2:
            probability: 0.5
            holding:
              fixed:
                delay: 14.428571
          req-103396835-11:
            probability: 0.125
            holding:
              fixed:
                delay: 14.428571
          req-103396835-5:
            probability: 0.25
            holding:
              fixed:
                delay: 14.428571
        req-103396835-19:
          req-103396835-14:
            probability: 1
            holding:
              fixed:
                delay: 4
        req-103396835-2:
          req-103396835-17:
            probability: 0.02439
            holding:
              fixed:
                delay: 42.404109
          req-103396835-11:
            probability: 0.287804
            holding:
              fixed:
                delay: 42.404109
          req-103396835-6:
            probability: 0.214634
            holding:
              fixed:
                delay: 42.404109
          req-103396835-3:
            probability: 0.029268
            holding:
              fixed:
                delay: 42.404109
          req-103396835-2:
            probability: 0.039024
            holding:
              fixed:
                delay: 42.404109
          req-103396835-5:
            probability: 0.004878
            holding:
              fixed:
                delay: 42.404109
          req-103396835-12:
            probability: 0.053658
            holding:
              fixed:
                delay: 42.404109
          req-103396835-1:
            probability: 0.014634
            holding:
              fixed:
                delay: 42.404109
          req-103396835-10:
            probability: 0.043902
            holding:
              fixed:
                delay: 42.404109
        req-103396835-20:
          req-103396835-20:
            probability: 0.5
            holding:
              fixed:
                delay: 45
        req-103396835-3:
          req-103396835-10:
            probability: 0.059701
            holding:
              fixed:
                delay: 77.543478
          req-103396835-2:
            probability: 0.074626
            holding:
              fixed:
                delay: 77.543478
          req-103396835-6:
            probability: 0.119402
            holding:
              fixed:
                delay: 77.543478
          req-103396835-17:
            probability: 0.014925
            holding:
              fixed:
                delay: 77.543478
          req-103396835-15:
            probability: 0.014925
            holding:
              fixed:
                delay: 77.543478
          req-103396835-12:
            probability: 0.104477
            holding:
              fixed:
                delay: 77.543478
          req-103396835-11:
            probability: 0.283582
            holding:
              fixed:
                delay: 77.543478
          req-103396835-3:
            probability: 0.014925
            holding:
              fixed:
                delay: 77.543478
        req-103396835-4:
          req-103396835-12:
            probability: 0.027777
            holding:
              fixed:
                delay: 89
          req-103396835-15:
            probability: 0.041666
            holding:
              fixed:
                delay: 89
          req-103396835-2:
            probability: 0.013888
            holding:
              fixed:
                delay: 89
          req-103396835-10:
            probability: 0.041666
            holding:
              fixed:
                delay: 89
          req-103396835-1:
            probability: 0.166666
            holding:
              fixed:
                delay: 89
          req-103396835-6:
            probability: 0.180555
            holding:
              fixed:
                delay: 89
        req-103396835-5:
          req-103396835-12:
            probability: 0.03125
            holding:
              fixed:
                delay: 47.222222
          req-103396835-5:
            probability: 0.03125
            holding:
              fixed:
                delay: 47.222222
          req-103396835-20:
            probability: 0.03125
            holding:
              fixed:
                delay: 47.222222
          req-103396835-6:
            probability: 0.03125
            holding:
              fixed:
                delay: 47.222222
          req-103396835-15:
            probability: 0.03125
            holding:
              fixed:
                delay: 47.222222
          req-103396835-2:
            probability: 0.0625
            holding:
              fixed:
                delay: 47.222222
          req-103396835-10:
            probability: 0.0625
            holding:
              fixed:
                delay: 47.222222
        req-103396835-6:
          req-103396835-15:
            probability: 0.063246
            holding:
              fixed:
                delay: 111.878143
          req-103396835-2:
            probability: 0.05903
            holding:
              fixed:
                delay: 111.878143
          req-103396835-12:
            probability: 0.040056
            holding:
              fixed:
                delay: 111.878143
          req-103396835-11:
            probability: 0.002108
            holding:
              fixed:
                delay: 111.878143
          req-103396835-9:
            probability: 0.000702
            holding:
              fixed:
                delay: 111.878143
          req-103396835-6:
            probability: 0.080112
            holding:
              fixed:
                delay: 111.878143
          req-103396835-4:
            probability: 0.028109
            holding:
              fixed:
                delay: 111.878143
          req-103396835-1:
            probability: 0.054813
            holding:
              fixed:
                delay: 111.878143
          req-103396835-3:
            probability: 0.001405
            holding:
              fixed:
                delay: 111.878143
          req-103396835-10:
            probability: 0.033028
            holding:
              fixed:
                delay: 111.878143
          req-103396835-8:
            probability: 0.000702
            holding:
              fixed:
                delay: 111.878143
        req-103396835-7:
          req-103396835-8:
            probability: 1
            holding:
              fixed:
                delay: 6
        req-103396835-8:
          req-103396835-6:
            probability: 0.5
            holding:
              fixed:
                delay: 3
          req-103396835-7:
            probability: 0.5
            holding:
              fixed:
                delay: 3
        req-103396835-9:
          req-103396835-18:
            probability: 0.5
            holding:
              fixed:
                delay: 8
          req-103396835-6:
            probability: 0.5
            holding:
              fixed:
                delay: 8
